# Generated by scripts/release.py in .github/workflows/release.yml.
cask "endu" do
  version "4.0.2"
  sha256 "dcab092c55efcb21c7ec8eb20d81e24fb9f5ccaf132db49cf25005e54c932471"

  url "https://github.com/publi0/endu/releases/download/v#{version}/Endu-#{version}.zip"
  name "Endu"
  desc "Dictation with live transcription and speech provider fallback"
  homepage "https://github.com/publi0/endu"

  depends_on arch: :arm64
  depends_on macos: :sequoia

  app "Endu.app"

  # The build is not notarized by Apple.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Endu.app"]
  end

  zap trash: [
    "~/Library/Application Support/hex-openrouter",
  ]
end
